### ISSUE TITLE
Running the test

### ISSUE THREAD

**Issue by tobibaum** [bymaths/probabilistic_triangulation#1]
Hi Authors, 

thanks for this great and inspiring work. I would like to try it on my data and experiment with it, but struggle to get it to run.

in the Readme, you write to run
```
python test.py --cfg config/H36M.yaml --weight checkpoints/H36M_point.pth
```

where do I get the `yaml` and `pth` files? and also, the `test.py` and `train.py` files do not seem to be present in the repo.

For running the notebook `A.ipynb`, I would need a file "/Users/byjiang/Code/Data/H36M_pose.npy". I do not see how this file would get created from `h36m-fetch`

Please advice on how to run a simple example (with weight-files) on a set of non-h36m images.

Thanks for your help!!
Tobi

**Comment by bymaths** [comment]
Thanks for the attention, there is some lack of clarity here. I'll update it as soon as I can.

**Comment by buzuyun** [comment]
@tobibaum Hi, have you solved that? I cannot run it as some files miss

**Comment by buzuyun** [comment]
@bymaths Hi, could you please update this repo?  i am interested about it

**Comment by bymaths** [comment]
Already updated
