### ISSUE TITLE
Camera parameters

### ISSUE THREAD

**Issue by SunQiu88** [bymaths/probabilistic_triangulation#2]
Hello,Thanks for your greate work! I want to know this method wether can predect the camera pose (including R and T) in the wild scene?and can you provide the inference  code by using a wild image?

**Comment by bymaths** [comment]
可以的，使用3d的人体姿态与2d人体姿态进行pnp即可得到相机姿态。
需要注意的点，对野外场景的鲁棒性与2D姿态估计的精度紧密相关，对于2D backbone训练时没有遇到过的复杂场景的时候可能失效。

**Comment by bymaths** [comment]
Yes, the camera pose can be obtained by pnp using the 3d body pose with the 2d body pose.
Note that the robustness to field scenes is closely related to the accuracy of the 2D pose estimation, and may fail for complex scenes not encountered during the 2D backbone training.

**Comment by apple32112311** [comment]
hello @@SunQiu88 , do you try to use a wild image successfull? How do you solve it? Thank you
