### ISSUE TITLE
About 8-point method!

### ISSUE THREAD

**Issue by Z-Z-J** [bymaths/probabilistic_triangulation#5]
I notice that you calculate the initial camera extrinsic parameters (rotation and translation) by using the eight-point method. Can you provide the code for this part?

**Comment by bymaths** [comment]
You can find the eight-point related code from the v1 folder.
The class CalibrationBatch in calibration.py can give a preliminary solution to the camera coordinates of the input point2d (batch).
The idea is
1. RANSAC estimation of essential mat from two cameras
2. Triangulation of two views to obtain 3D
3. Pnp each view using 3d and 2d
4. All views triangulaiton get more stable 3d

some advices:
1. The effect will be better with more iterations.
2. If you are dealing with video, it is recommended to use multiple frames when estimating. Personal experience is that you can get very good results with just a dozen frames (the main reason for effectiveness is that it can make up for the error in 2d. If the 2d is accurate, the number of frames can also be reduced)
