### ISSUE TITLE
How to solve the output of the bones is the root node for (0,0,0) coordinates？

### ISSUE THREAD

**Issue by weibao1001** [bymaths/probabilistic_triangulation#6]
Hello, your work is very good, I would like to ask, your output bones are all root nodes (0,0,0), what should I do to get the translation information, so that it is not (0,0,0)？

**Comment by bymaths** [comment]
For a single frame, you can only get the result that the root joint is (0,0,0) (because there is no information about the reference object of the world coordinate system).
If it is a video, the displacement and rotation of the heel joint can be obtained through the difference in camera coordinates calculated between frames.

**Comment by weibao1001** [comment]
> For a single frame, you can only get the result that the root joint is (0,0,0) (because there is no information about the reference object of the world coordinate system). If it is a video, the displacement and rotation of the heel joint can be obtained through the difference in camera coordinates calculated between frames.

Okay, thank you for your reply. I have another question to ask you. If I want to obtain the three-dimensional coordinates in the camera coordinate system, what should I do? Do I need to obtain the camera's pose by solving the PnP (Perspective-n-Point) problem?

**Comment by bymaths** [comment]
> > For a single frame, you can only get the result that the root joint is (0,0,0) (because there is no information about the reference object of the world coordinate system). If it is a video, the displacement and rotation of the heel joint can be obtained through the difference in camera coordinates calculated between frames.
> 
> Okay, thank you for your reply. I have another question to ask you. If I want to obtain the three-dimensional coordinates in the camera coordinate system, what should I do? Do I need to obtain the camera's pose by solving the PnP (Perspective-n-Point) problem?

Yes, directly output 3D results and 2D results for pnp
