### ISSUE TITLE
训练代码中没有体现“Probabilistic Triangulation”

### ISSUE THREAD

**Issue by makalo** [bymaths/probabilistic_triangulation#8]
看了一下训练测试代码，发现在训练过程中，并没有体现“Probabilistic Triangulation”过程。

**Comment by bymaths** [comment]
The corresponding method in the paper is in V1
I did more tests. I tried not to add explicit calculations (the process of iteratively seeking distribution, this process is too slow), but directly extracted the features at the corresponding positions and put them together. There was no need to do so during training. Adding camera pose, we found that the accuracy is also similar. This shows that the network can actually replace the iterative optimization process above, and there is really no need to go around in a circle to find the iterative camera pose.
